//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

  public partial class Book
    {
        public int BookID { get; set; }
        [Required(ErrorMessage ="This field is required")]
        public string BName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string BAuthor { get; set; }
        public string BDetail { get; set; }
        public int BFee { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public bool BAvailability { get; set; }
    }
}
